# Generated by Django 4.2.3 on 2023-07-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
